# -*- coding: utf-8 -*-
"""程式專題.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kNO9jnVyG0Caymhqc1E1OBImU362lD-G

資料查詢(星座列表，要有座標、相對亮度、範圍)(#行星#星團#星雲)~20min

選擇觀測方式:肉眼(望眼鏡)
輸入地點，連接查詢緯度(光害)
輸入觀測時間
計算仰角、亮度
推薦三個星體(亮度第一，仰角第二)並顯示相關資訊
刷新換下三個
"""
import pandas as pd
import astropy.units as u
import numpy as np
import matplotlib.pyplot as plt
import os
import datetime
from astropy.time import Time
from astropy.coordinates import SkyCoord, EarthLocation, AltAz
from geopy.geocoders import Nominatim


def get_star_recommendations(csv_path, address_str, obs_time_str):
    """
    輸入地點與時間，推薦目前最適合觀測的 3 顆亮星
    """
    # 1. 載入星圖資料 (使用你提供的 hyg_hr_stars.csv)
    csv_path = os.path.join(os.path.dirname(__file__),"hyg_hr_stars.csv")
    df = pd.read_csv(csv_path)

    condition = True
    # 2. 連結地圖取得緯度 (使用 geopy 進行地理編碼)
    geolocator = Nominatim(user_agent="star_tracker")
    location_data = geolocator.geocode(address_str)
    if not location_data:
        condition = False
        return None, condition

    lat = location_data.latitude
    lon = location_data.longitude
    print(f"觀測地點：{location_data.address} (緯度: {lat:.2f}, 經度: {lon:.2f})")

    # 3. 定義觀測者位置與時間
    # 假設輸入時間為台灣時間 (UTC+8)，轉換為 UTC 以供 astropy 計算
    observer_location = EarthLocation(lat=lat*u.deg, lon=lon*u.deg, height=0*u.m)
    obs_time = Time(obs_time_str) - 8*u.hour  # 修正時區偏移

    # 4. 座標轉換 (RA/Dec -> Alt/Az)
    # RA 以小時 (h) 表示，Dec 以度 (deg) 表示
    star_coords = SkyCoord(ra=df['RA2000'].values*u.hour,
                           dec=df['DEJ2000'].values*u.deg,
                           frame='icrs')

    # 計算地平座標框架
    altaz_frame = AltAz(obstime=obs_time, location=observer_location)
    altaz_results = star_coords.transform_to(altaz_frame)

    # 將計算結果回填至資料表
    df['altitude'] = altaz_results.alt.deg
    df['azimuth'] = altaz_results.az.deg

    # 5. 篩選與推薦條件
    # 推薦條件：仰角 > 15度，亮度 < 6等 (數值越小越亮)
    recommended = df[(df['altitude'] > 15) & (df['Vmag'] < 6.0)].copy()

    # 以亮度進行排序 (由亮至暗)
    recommended = recommended.sort_values(by='Vmag').head(3)

    return recommended, condition

def draw_compass(azimuth):
    fig, ax = plt.subplots()

    # 畫圓
    circle = plt.Circle((0, 0), 1, fill=False)
    ax.add_artist(circle)

    # 角度轉弧度（0°在北）
    angle = np.deg2rad(90 - azimuth)

    # 箭頭
    ax.arrow(0, 0, np.cos(angle), np.sin(angle),
             head_width=0.1, length_includes_head=True)

    # 標示方向
    ax.text(0, 1.1, "N", ha='center')
    ax.text(1.1, 0, "E", va='center')
    ax.text(0, -1.2, "S", ha='center')
    ax.text(-1.2, 0, "W", va='center')

    ax.set_aspect('equal')
    ax.axis('off')

    return fig

